In [1]:
import numpy as np

In [2]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
b=np.arange(1,10)
b.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
c=np.random.randint(1,10,9).reshape(3,3)

In [5]:
x=np.array((1,2,3))

In [6]:
x.ndim

1

In [7]:
y=x.reshape(1,3)
y

array([[1, 2, 3]])

In [8]:
y.ndim

2