In [1]:
import numpy as np

In [3]:
a=np.random.randint(1,20,12)
a

array([17, 18,  3, 14,  2,  3, 18,  5, 17,  4, 11, 12])

In [4]:
np.split(a,[5]) #second parameter(s) is(are) index of split operation

[array([17, 18,  3, 14,  2]), array([ 3, 18,  5, 17,  4, 11, 12])]

In [5]:
np.split(a,[2, 5])

[array([17, 18]), array([ 3, 14,  2]), array([ 3, 18,  5, 17,  4, 11, 12])]

In [6]:
x,y,z,q = np.split(a,[2,5,8])

In [7]:
x

array([17, 18])

In [8]:
y

array([ 3, 14,  2])

In [9]:
z

array([ 3, 18,  5])

In [11]:
#dimension number is larger than 1, what should we do?
b=np.random.randint(0,20,12).reshape(3,4)
b

array([[19, 17, 10,  2],
       [17, 17, 18,  1],
       [ 5,  2,  2, 11]])

In [12]:
np.split(b,[1])

[array([[19, 17, 10,  2]]),
 array([[17, 17, 18,  1],
        [ 5,  2,  2, 11]])]

In [13]:
np.split(b,[1,2])

[array([[19, 17, 10,  2]]),
 array([[17, 17, 18,  1]]),
 array([[ 5,  2,  2, 11]])]

In [14]:
np.split(b,[2])

[array([[19, 17, 10,  2],
        [17, 17, 18,  1]]),
 array([[ 5,  2,  2, 11]])]

In [15]:
#this case, split function similarly works with vsplit function
np.vsplit(b,[2])

[array([[19, 17, 10,  2],
        [17, 17, 18,  1]]),
 array([[ 5,  2,  2, 11]])]

In [16]:
#if we want split horizontally, we should use hsplit function
np.hsplit(b,[2])

[array([[19, 17],
        [17, 17],
        [ 5,  2]]),
 array([[10,  2],
        [18,  1],
        [ 2, 11]])]