In [2]:
import numpy as np

In [3]:
a=np.random.randint(0,15,5)
a

array([ 3,  0, 14, 13,  6])

In [4]:
np.sort(a)

array([ 0,  3,  6, 13, 14])

In [8]:
# we will use argsort function for review the index numbers of sorted array elements, before sorted case
b=np.argsort(a)
b

array([1, 0, 4, 3, 2])