In [1]:
import numpy as np

In [4]:
a=np.random.randint(20,size=10)
a

array([18,  4,  8,  0,  6, 12,  5, 16, 15,  0])

In [5]:
a[0]

18

In [6]:
a[5] = 14
a

array([18,  4,  8,  0,  6, 14,  5, 16, 15,  0])

In [7]:
b=np.random.randint(0,12, size=(3,4))
b

array([[ 4,  1,  7, 11],
       [11,  9,  2,  2],
       [ 8,  4,  6,  7]])

In [9]:
b[0,0]

4

In [10]:
b[1,3]

2

In [11]:
a[0:2]

array([18,  4])

In [13]:
a[:4]

array([18,  4,  8,  0])

In [14]:
a[::2]

array([18,  8,  6,  5, 15])

In [15]:
c=np.random.randint(0,20,size=(5,4))
c

array([[17, 10,  4,  6],
       [18, 15, 15, 15],
       [ 3,  3,  3, 10],
       [ 2,  4,  3, 18],
       [ 5, 17, 17,  6]])

In [20]:
var1 = c[3,:] #, is important bc
print("var1",var1)
var2 = c[3:] #different
print("var2",var2)

var1 [ 2  4  3 18]
var2 [[ 2  4  3 18]
 [ 5 17 17  6]]


In [21]:
c[:,2]

array([ 4, 15,  3,  3, 17])

In [22]:
c[3:,:3]

array([[ 2,  4,  3],
       [ 5, 17, 17]])

In [23]:
c[1:3, 1:3]

array([[15, 15],
       [ 3,  3]])