In [1]:
import numpy as np

In [2]:
x=np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [4]:
z=np.copy(x)
z

array([1, 2, 3, 4, 5])

In [5]:
z[0] = 27
z

array([27,  2,  3,  4,  5])

In [6]:
x

array([1, 2, 3, 4, 5])