In [1]:
import numpy as np

In [2]:
a=np.arange(1,8)
a

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
a>5

array([False, False, False, False, False,  True,  True])

In [4]:
a<=5

array([ True,  True,  True,  True,  True, False, False])

In [5]:
np.sum(a>=5) #function returns item count of fit with condition

3

In [8]:
np.sum((a>2) & (a<6))

3

In [10]:
b=np.random.randint(1,10,(3,3))
b

array([[4, 2, 6],
       [3, 2, 7],
       [5, 1, 8]])

In [12]:
b>5

array([[False, False,  True],
       [False, False,  True],
       [False, False,  True]])

In [13]:
np.sum(b>5)

3

In [17]:
np.sum(b>5,axis=1) #item count of fit with condition, row based.

array([1, 1, 1])

In [19]:
np.sum(b>5, axis=0) #item count of fit with condition, column based.

array([0, 0, 3])

In [22]:
#all function compares all elements with condition statement. If all elements fit, returns true
c=np.random.randint(1,10,(4,3))
c

array([[6, 3, 5],
       [6, 7, 2],
       [9, 8, 6],
       [1, 6, 8]])

In [24]:
np.all(c>0)

True

In [25]:
np.all(c>2)

False

In [28]:
#all function compares all elements with condition statement. If any of elements fit, returns true.
np.any(c>1)

True

In [29]:
np.any(c<1)

False