In [44]:
import numpy as np

In [45]:
a=np.random.randint(1,20,10)
a

array([ 6, 12, 16, 16,  5,  1, 15, 11,  5, 16])

In [46]:
max(a) #returns maximum value

16

In [47]:
min(a) #returns minimum value

1

In [48]:
np.argmax(a) #returns index number of maximum value

2

In [49]:
np.argmin(a) #returns index number of maximum value

5

In [50]:
np.sum(a) #returns the total value of all elements

103

In [51]:
b = np.random.randint(1,21,(4,5))
b

array([[ 1, 16, 14,  4,  7],
       [19,  8, 13,  4, 15],
       [19,  9,  7, 13,  6],
       [12, 14,  1, 18, 10]])

In [52]:
sum(b) #returns the total value of each row

array([51, 47, 35, 39, 38])

In [53]:
b.sum(axis=0) #returns the total value of each row

array([51, 47, 35, 39, 38])

In [54]:
b.sum(axis=1) ##returns the total value of each column

array([42, 59, 54, 55])

In [55]:
b.sum().sum() #returns the total value of all elements

210

In [56]:
b.mean() #returns average value of array

10.5

In [58]:
np.median(b) #returns median of array

11.0

In [59]:
b.std() #returns standard deviation

5.518151864528558