In [31]:
import numpy as np

In [32]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [33]:
a+5

array([6, 7, 8, 9])

In [34]:
a*2

array([2, 4, 6, 8])

In [35]:
b=np.arange(5,9)
b

array([5, 6, 7, 8])

In [36]:
a+b #same dimensions and same index count

array([ 6,  8, 10, 12])

In [37]:
c=np.arange(9,14)
c

array([ 9, 10, 11, 12, 13])

In [38]:
# a+c --> gets an error because different index counts

In [39]:
d=np.arange(1,10).reshape(3,3)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
#a+d --> gets an error different index counts#

In [41]:
e=np.arange(1,4)
e

array([1, 2, 3])

In [42]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
e+d #no error, values ​​of array e are added to each row of array d

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [44]:
f=np.arange(1,4).reshape(3,1)
f

array([[1],
       [2],
       [3]])

In [45]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
f+d #no error, values ​​of array e are added to each row of array d

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])