In [1]:
import numpy as np


In [2]:
##Let's specify the type of the numpy array with the type function. Because there are no arrays in core python.
a = np.array([1,3,5,7,9])
type(a)

numpy.ndarray

In [6]:
#So how can we convert a list, tupble to a numpy array?
list1 = [0,2,4,6,8]
tuple1 = (17,43,26,41,34)
numpyArrayFromList = np.array(list1)
numpyArrayFromTuple = np.array(tuple1)
type(numpyArrayFromList)
type(numpyArrayFromTuple)

numpy.ndarray

In [8]:
#Let's say that only one of the elements of our numpy array is of type float. The others are of type int.
b = np.array([1,2,3,4,5,6.8])
for i in b:
  print(type(i))
  #It also converted the int type to float type because all the elements in the numpy array must be of the same type. This is a feature of the numpy array structure.

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [11]:
#However, if we pass a data type that we specify to the dtype parameter as an argument, the data in the array will be kept in that type.
c = np.array([1,2,3,4,5.2], dtype=np.int32)
for i in c:
  print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [16]:
#Let's show a few of the frequently used function provided by the numpy library:
#For our matrix generation needs etc.
print(np.zeros(10,dtype="int8"))
print(np.ones(12) * 6)
print(np.full(14,7))

[0 0 0 0 0 0 0 0 0 0]
[6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
[7 7 7 7 7 7 7 7 7 7 7 7 7 7]
