In [1]:
import numpy as np

In [2]:
np.array([(1,2,3),(4,5,6)]) #2d

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.array([(1,2,3),(4,5,6),(7,8,9)]) #3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])