In [1]:
import numpy as np

In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [5]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [6]:
np.linspace(0,30,3)

array([ 0., 15., 30.])

In [7]:
np.random.rand(5)

array([0.53889662, 0.35754651, 0.43428058, 0.46754424, 0.58606599])

In [8]:
np.random.rand(2,3) # 0<=values<1

array([[0.71337081, 0.36383313, 0.76622307],
       [0.43665783, 0.62052596, 0.65326359]])

In [10]:
np.random.normal(0,1,(3,3))

array([[-0.67489368,  1.89624764, -2.57993753],
       [ 0.42000446, -0.62177493, -0.42050189],
       [-1.21265423, -1.19132773, -1.80546158]])

In [11]:
np.random.normal(10,3,(3,3))

array([[12.05629564, 12.53387777,  4.44577802],
       [ 9.37292588,  6.88838979,  8.47389317],
       [ 9.57974437, 14.30195477, 13.45903376]])

In [12]:
np.random.randint(0,10)

9

In [13]:
np.random.randint(0,10,8)

array([6, 6, 6, 8, 8, 3, 5, 6])

In [14]:
np.random.randint(0,10,(4,2))

array([[0, 7],
       [1, 6],
       [7, 8],
       [9, 2]])

In [15]:
np.random.randn(3,4)

array([[-1.22835006, -0.42961849,  2.07623867, -0.04733242],
       [-1.47777057,  0.43496794,  1.13919971,  0.23020229],
       [ 0.0371735 ,  1.11066545,  1.59558823, -0.18509354]])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])