In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,10,size=10)
a

array([3, 6, 4, 8, 8, 2, 6, 4, 3, 8])

In [3]:
a.ndim #dimension info

1

In [4]:
a.shape #show dimensions

(10,)

In [5]:
a.size #size

10

In [6]:
a.dtype #type of dimension's values

dtype('int64')

In [7]:
type(a)

numpy.ndarray

In [11]:
b = np.random.randint(1,20,(4,3))
b

array([[ 4,  7, 10],
       [15, 15,  3],
       [12, 16,  9],
       [ 5, 16, 11]])

In [13]:
b.ndim #dimension count

2

In [14]:
b.dtype

dtype('int64')

In [17]:
c = np.random.randint(1,20,(4,3,5))
c

array([[[ 5, 16, 18,  6,  1],
        [14, 15,  6,  8, 16],
        [ 8, 10,  5, 10, 15]],

       [[19, 11, 19,  4, 14],
        [19,  4, 19, 17,  5],
        [11,  2, 13, 10, 16]],

       [[10, 10,  1,  9, 12],
        [ 9, 17,  6,  1, 15],
        [15, 11, 17,  7, 18]],

       [[ 1, 11, 15,  3, 10],
        [14,  4, 14,  5,  5],
        [ 8, 15, 12,  3,  5]]])

In [18]:
c.ndim

3

In [19]:
c.shape

(4, 3, 5)