In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
x=np.array(([1,2,3], [4,5,6]))
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
y=np.array(([7,8,9], [10,11,12]))
y

array([[ 7,  8,  9],
       [10, 11, 12]])

In [6]:
np.concatenate([x,y]) #axis = 0 --> default parameter value

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
np.concatenate([x,y], axis=1) #axis = 1

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [10]:
#if we have different dimension numbers and we want concatenate, interpreter gives error
z = np.array([13,14,15])
#np.concatenate([x,z]) value error, we must use another function for this operation