In [8]:
import numpy as np

In [9]:
x= np.array(([1, 2, 3], [4, 5, 6]))
y=np.array(([7, 8, 9]))
print(x)
print(y)

[[1 2 3]
 [4 5 6]]
[7 8 9]


In [10]:
np.vstack([x, y]) # vstack --> vertical merge function different size arrays

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a=np.array(([1, 1, 1], [1, 1, 1]))
b=np.array(([1, 1], [1, 1]))
#np.vstack([a,b]) #value error because it has empty fields in vertical merge

"""
#np.vstack([a,b]) #value An error occurred because there were empty spaces in the vertical join.
In such cases, the hstack function is used instead of vstack.
The hstack function prevents empty spaces and errors by joining horizontally when arrays of the same size have different number of elements.
"""
np.hstack([a,b])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])